### ISSUE TITLE
Login Question

### ISSUE THREAD

**Issue by watnalldt** [django-forge/forge#27]
Trying out Forge.
Creating a user through the admin panel does not then allow them to login with either their username or email.
If this is done via the command line or signup form then there is no issue.
In our case there is a need to create users through the admin panel.
Am I missing something?

**Comment by davegaeddert** [comment]
Weird. What does it tell you? Just that the username/password isn't correct?

I just tried it on a fresh install from the quickstart and it seemed to work fine. Is this along the lines of what you did?

https://user-images.githubusercontent.com/649496/172885071-7f7000b0-99c8-4834-9f1a-93d90225ebc9.mp4

Only thing that comes to mind immediately is to 1) make sure you got the password right and 2) make sure you're looking at the right site (i.e. Heroku if you've deployed to Heroku, local if you're working locally). Have you made any changes to `settings.py` or anything?

**Comment by watnalldt** [comment]
I deleted the project and started again from the quick install and everything worked. I am not sure what the issue was but thanks for the quick response

**Comment by davegaeddert** [comment]
No problem 👍 let me know if you run into any other questions!
